#cloud-config
hostname: mariadb-vm
timezone: Europe/Paris

package_update: true
package_upgrade: true
packages:
  - mariadb-server

runcmd:
  - |
    # Variables
    DB_NAME="wordpress"
    DB_USER="wpuser"
    DB_PASS="Motdepasse123!"

    # Enable and start MariaDB
    systemctl enable mariadb
    systemctl start mariadb

    # Configure MariaDB to listen on all interfaces
    sed -i "s/^bind-address\s*=.*/bind-address = 0.0.0.0/" /etc/mysql/mariadb.conf.d/50-server.cnf
    systemctl restart mariadb

    # Create database and user
    mysql -u root -e "CREATE DATABASE IF NOT EXISTS ${DB_NAME} CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;"
    mysql -u root -e "CREATE USER IF NOT EXISTS '${DB_USER}'@'%' IDENTIFIED BY '${DB_PASS}';"
    mysql -u root -e "GRANT ALL PRIVILEGES ON ${DB_NAME}.* TO '${DB_USER}'@'%';"
    mysql -u root -e "FLUSH PRIVILEGES;"

final_message: "MariaDB installation and WordPress database/user setup completed."