#cloud-config
hostname: wordpress-vm
timezone: Europe/Paris

package_update: true
package_upgrade: true
packages:
  - apache2
  - php
  - php-mysql
  - libapache2-mod-php
  - curl
  - unzip

write_files:
  - path: /etc/environment
    permissions: '0644'
    content: |
      WP_DB_NAME=${WP_DB_NAME}
      WP_DB_USER=${WP_DB_USER}
      WP_DB_PASS=${WP_DB_PASS}
      WP_DB_HOST=${WP_DB_HOST}

runcmd:
  # Charger les variables denvironnement
  - source /etc/environment

  # Télécharger et installer WordPress
  - curl -O https://wordpress.org/latest.tar.gz
  - tar -xzf latest.tar.gz
  - cp -r wordpress/* /var/www/html/
  - chown -R www-data:www-data /var/www/html/
  - chmod -R 750 /var/www/html/
  - rm /var/www/html/index.html || true

  # Configurer wp-config.php avec les variables
  - cp /var/www/html/wp-config-sample.php /var/www/html/wp-config.php
  - sed -i "s/define( 'DB_NAME', '' );/define( 'DB_NAME', '${WP_DB_NAME}' );/" /var/www/html/wp-config.php
  - sed -i "s/define( 'DB_USER', '' );/define( 'DB_USER', '${WP_DB_USER}' );/" /var/www/html/wp-config.php
  - sed -i "s/define( 'DB_PASSWORD', '' );/define( 'DB_PASSWORD', '${WP_DB_PASS}' );/" /var/www/html/wp-config.php
  - sed -i "s/define( 'DB_HOST', '' );/define( 'DB_HOST', '${WP_DB_HOST}' );/" /var/www/html/wp-config.php

  # Redémarrer Apache
  - systemctl restart apache2

final_message: "WordPress installé avec variables denvironnement."
