#cloud-config
hostname: wordpress-vm
timezone: Europe/Paris

package_update: true
package_upgrade: true
packages:
  - apache2
  - php
  - php-mysql
  - libapache2-mod-php
  - curl
  - unzip

runcmd:
  - |
    # Declare variables
    DB_NAME="wordpress"
    DB_USER="wpuser"
    DB_PASS="Motdepasse123!"
    DB_HOST="10.2.1.4"

    # Download and install WordPress
    curl -O https://wordpress.org/latest.tar.gz
    tar -xzf latest.tar.gz
    cp -r wordpress/* /var/www/html/
    chown -R www-data:www-data /var/www/html/
    chmod -R 755 /var/www/html/
    rm /var/www/html/index.html || true

    # Configure wp-config.php using variables
    cp /var/www/html/wp-config-sample.php /var/www/html/wp-config.php
    sed -i "s/database_name_here/${DB_NAME}/" /var/www/html/wp-config.php
    sed -i "s/username_here/${DB_USER}/" /var/www/html/wp-config.php
    sed -i "s/password_here/${DB_PASS}/" /var/www/html/wp-config.php
    sed -i "s/localhost/${DB_HOST}/" /var/www/html/wp-config.php

    # Restart Apache
    systemctl restart apache2

final_message: "WordPress installation completed with hardcoded variables."
